### ISSUE TITLE
Incorrect matching

### ISSUE THREAD

**Issue by manbearpig2012** [SpaceK33z/plex2netflix#20]
So finally got plex2netflix running, ran it on my library, and when i was skimming through noticed something. It may not be 100% accurate, as Stranger Things, a netflix original series, got paired as [not on netflix](https://cdn.discordapp.com/attachments/248227602307743744/263823750900875286/unknown.png)

**Comment by SpaceK33z** [comment]
I'm depending on a non-official Netflix API, since Netflix doesn't have a public API anymore. It looks like that API doesn't return anything when you search on Stranger Things: https://netflixroulette.net/api/v2/usa/imdb/?imdbId=tt4574334 doesn't have a `netflix_id`.

We need to find a new non-official API that allows to search on Netflix using a imdb ID and/or with title and year. Any help with this is greatly appreciated.

**Comment by SpaceK33z** [comment]
Perhaps we could search on [AllFlicks](https://www.allflicks.net/), they seem to have an up-to-date database. They don't really have a public API, so possibly they won't like it.

**Comment by SpaceK33z** [comment]
Update: I emailed the guy behind uNoGS and he gave me access to the API. I'll need to build a special backend however to cache the API and to keep the API token secret, so that will take some time.

**Comment by SpaceK33z** [comment]
I implemented the uNoGS API and it's released with `plex2netflix@0.5.0`. @manbearpig2012 it should work again now :).
